### ISSUE TITLE
Test ticket: Simple change in dashboard

### ISSUE THREAD

**Issue by franceslou1818** [adriancpwong/adriancpwong.github.io#2]
There is an incorrect value in the dashboard page. Change this from 743 to 734

How to recreate the issue:

1. Go to https://donate.semescotland.co.uk
1. Click the donate button - this will take you to another page
1. Click the button "Preview our user dashboard"
1. "743 me points" should be "734 me points"

**Comment by adriancpwong** [comment]
Tested. Looks good.
