### ISSUE TITLE
Change description on donation page

### ISSUE THREAD

**Issue by adriancpwong** [adriancpwong/adriancpwong.github.io#3]
Incorrect punctuation on main donation page. Remove exclamation mark.

How to recreate the issue:

1. Go to http://donate.semescotland.co.uk
2. There should be no exclamation mark at the end of the description

**Comment by franceslou1818** [comment]
Tested. Looks good. ready for merge.

**Comment by franceslou1818** [comment]
Live testing passed. Closing ticket.
